// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofile/Player.proto

package com.proto;

public final class PlayerModule {
  private PlayerModule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 playerId = 1;
    boolean hasPlayerId();
    int getPlayerId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // repeated int32 gae = 3;
    java.util.List<java.lang.Integer> getGaeList();
    int getGaeCount();
    int getGae(int index);
    
    // optional .Player.SEX sex = 4 [default = MALE];
    boolean hasSex();
    com.proto.PlayerModule.Player.SEX getSex();
  }
  public static final class Player extends
      com.google.protobuf.GeneratedMessage
      implements PlayerOrBuilder {
    // Use Player.newBuilder() to construct.
    private Player(Builder builder) {
      super(builder);
    }
    private Player(boolean noInit) {}
    
    private static final Player defaultInstance;
    public static Player getDefaultInstance() {
      return defaultInstance;
    }
    
    public Player getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.PlayerModule.internal_static_Player_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.PlayerModule.internal_static_Player_fieldAccessorTable;
    }
    
    public enum SEX
        implements com.google.protobuf.ProtocolMessageEnum {
      MALE(0, 0),
      WOMAN(1, 1),
      ;
      
      public static final int MALE_VALUE = 0;
      public static final int WOMAN_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static SEX valueOf(int value) {
        switch (value) {
          case 0: return MALE;
          case 1: return WOMAN;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<SEX>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<SEX>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SEX>() {
              public SEX findValueByNumber(int number) {
                return SEX.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.proto.PlayerModule.Player.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final SEX[] VALUES = {
        MALE, WOMAN, 
      };
      
      public static SEX valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private SEX(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Player.SEX)
    }
    
    private int bitField0_;
    // required int32 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private int playerId_;
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPlayerId() {
      return playerId_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated int32 gae = 3;
    public static final int GAE_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> gae_;
    public java.util.List<java.lang.Integer>
        getGaeList() {
      return gae_;
    }
    public int getGaeCount() {
      return gae_.size();
    }
    public int getGae(int index) {
      return gae_.get(index);
    }
    
    // optional .Player.SEX sex = 4 [default = MALE];
    public static final int SEX_FIELD_NUMBER = 4;
    private com.proto.PlayerModule.Player.SEX sex_;
    public boolean hasSex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.proto.PlayerModule.Player.SEX getSex() {
      return sex_;
    }
    
    private void initFields() {
      playerId_ = 0;
      name_ = "";
      gae_ = java.util.Collections.emptyList();;
      sex_ = com.proto.PlayerModule.Player.SEX.MALE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < gae_.size(); i++) {
        output.writeInt32(3, gae_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(4, sex_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < gae_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(gae_.get(i));
        }
        size += dataSize;
        size += 1 * getGaeList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, sex_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.proto.PlayerModule.Player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.proto.PlayerModule.Player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.proto.PlayerModule.Player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.proto.PlayerModule.Player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.proto.PlayerModule.Player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.proto.PlayerModule.Player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.proto.PlayerModule.Player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.proto.PlayerModule.Player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.proto.PlayerModule.Player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.proto.PlayerModule.Player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.proto.PlayerModule.Player prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.proto.PlayerModule.PlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.PlayerModule.internal_static_Player_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.PlayerModule.internal_static_Player_fieldAccessorTable;
      }
      
      // Construct using com.proto.PlayerModule.Player.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        gae_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = com.proto.PlayerModule.Player.SEX.MALE;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.PlayerModule.Player.getDescriptor();
      }
      
      public com.proto.PlayerModule.Player getDefaultInstanceForType() {
        return com.proto.PlayerModule.Player.getDefaultInstance();
      }
      
      public com.proto.PlayerModule.Player build() {
        com.proto.PlayerModule.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.proto.PlayerModule.Player buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.proto.PlayerModule.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.proto.PlayerModule.Player buildPartial() {
        com.proto.PlayerModule.Player result = new com.proto.PlayerModule.Player(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          gae_ = java.util.Collections.unmodifiableList(gae_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.gae_ = gae_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sex_ = sex_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.PlayerModule.Player) {
          return mergeFrom((com.proto.PlayerModule.Player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.proto.PlayerModule.Player other) {
        if (other == com.proto.PlayerModule.Player.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (!other.gae_.isEmpty()) {
          if (gae_.isEmpty()) {
            gae_ = other.gae_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureGaeIsMutable();
            gae_.addAll(other.gae_);
          }
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 24: {
              ensureGaeIsMutable();
              gae_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addGae(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.proto.PlayerModule.Player.SEX value = com.proto.PlayerModule.Player.SEX.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                sex_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 playerId = 1;
      private int playerId_ ;
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPlayerId() {
        return playerId_;
      }
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // repeated int32 gae = 3;
      private java.util.List<java.lang.Integer> gae_ = java.util.Collections.emptyList();;
      private void ensureGaeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          gae_ = new java.util.ArrayList<java.lang.Integer>(gae_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<java.lang.Integer>
          getGaeList() {
        return java.util.Collections.unmodifiableList(gae_);
      }
      public int getGaeCount() {
        return gae_.size();
      }
      public int getGae(int index) {
        return gae_.get(index);
      }
      public Builder setGae(
          int index, int value) {
        ensureGaeIsMutable();
        gae_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addGae(int value) {
        ensureGaeIsMutable();
        gae_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllGae(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureGaeIsMutable();
        super.addAll(values, gae_);
        onChanged();
        return this;
      }
      public Builder clearGae() {
        gae_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      
      // optional .Player.SEX sex = 4 [default = MALE];
      private com.proto.PlayerModule.Player.SEX sex_ = com.proto.PlayerModule.Player.SEX.MALE;
      public boolean hasSex() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.proto.PlayerModule.Player.SEX getSex() {
        return sex_;
      }
      public Builder setSex(com.proto.PlayerModule.Player.SEX value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        sex_ = value;
        onChanged();
        return this;
      }
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = com.proto.PlayerModule.Player.SEX.MALE;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Player)
    }
    
    static {
      defaultInstance = new Player(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Player)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Player_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Player_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protofile/Player.proto\"q\n\006Player\022\020\n\010pl" +
      "ayerId\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\013\n\003gae\030\003 \003(\005\022" +
      "\036\n\003sex\030\004 \001(\0162\013.Player.SEX:\004MALE\"\032\n\003SEX\022\010" +
      "\n\004MALE\020\000\022\t\n\005WOMAN\020\001B\031\n\tcom.protoB\014Player" +
      "Module"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Player_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Player_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Player_descriptor,
              new java.lang.String[] { "PlayerId", "Name", "Gae", "Sex", },
              com.proto.PlayerModule.Player.class,
              com.proto.PlayerModule.Player.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
